version: '3.8'

services:
  tomcat:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    container_name: pablo-calvo-tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/conf:/usr/local/tomcat/conf
      - ./tomcat/logs:/usr/local/tomcat/logs